name: Prompt Review
run-name: "Prompt Review — PR #${{ github.event.pull_request.number }}"

on:
  pull_request:
    paths:
      - 'prompts/**'   # Adjust to match where your prompt files live

permissions:
  contents: read
  pull-requests: write
  issues: write       # Required — GitHub's PR comment API uses the issues endpoint

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required — the action needs git history to compare versions

      - uses: HOSHO-AI/Hosho-prompt-optimization-public@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          api_key: ${{ secrets.HOSHO_API_KEY }}
          prompt_path: prompts/
          # system_overview: docs/system-overview.md   # Optional — see step 4 in README
